module.exports = [
    {"distributorId":"124752","name":"MEDAK DISTRICT POLICE GAS SERVICE"},
    {"distributorId":"125461","name":"VISAKHA CEMENT INDUSTRIES,"},
    {"distributorId":"125478","name":"BRINDAVAN GAS AGENCY"},
    {"distributorId":"125482","name":"BDL EMPLOYEES COOP SOCIETY"},
    {"distributorId":"125484","name":"NAMRATA GAS AGENCY"},
    {"distributorId":"125491","name":"KALPANA GAS AGENCY"},
    {"distributorId":"125502","name":"MADUR GAS AGENCY"},
    {"distributorId":"125504","name":"ORDNANCE GAS SERVICE"},
    {"distributorId":"125505","name":"GRUHALAKSHMI ENTERPRISES"},
    {"distributorId":"125506","name":"CCECCS LTD"},
    {"distributorId":"189247","name":"MANISHA INDANE"},
    {"distributorId":"191443","name":"SPANDANA INDANE"},
    {"distributorId":"230785","name":"SAPTHAGIRI INDANE"},
    {"distributorId":"231098","name":"SAMBHAVI INDANE"},
    {"distributorId":"235155","name":"VAJRA INDANE"},
    {"distributorId":"237144","name":"KUBERA INDANE"},
    {"distributorId":"240817","name":"JAI BHAVANI INDANE"},
    {"distributorId":"256707","name":"SRI GURU RAGHAVENDRA INDANE G/V"},
    {"distributorId":"260132","name":"K.S.S INDANE GRAMIN VITRAK"},
    {"distributorId":"260471","name":"JAI DURGA BHAVANI INDANE GRAMI"},
    {"distributorId":"261378","name":"SRI SANTOSHI INDANE GRAMIN VIT"},
    {"distributorId":"272042","name":"K.N.G INDANE GRAMIN VITRAK"},
    {"distributorId":"273104","name":"S.R.R INDANE GRAMIN VITRAK"},
    {"distributorId":"276231","name":"SREE MITHRA GRAMIN VITRAK"},
    {"distributorId":"286302","name":"RADHA INDANE"},
    {"distributorId":"286526","name":"BAI REDDY INDANE GRAMIN VITRAK"},
    {"distributorId":"287282","name":"SIRI NANDANA INDANE"},
    {"distributorId":"288072","name":"AMBA BHAVANI INDANE"},
    {"distributorId":"288169","name":"SREE NARASIMHA SWAMY INDANE GRAMIN"},
    {"distributorId":"289008","name":"MANASA INDANE"},
    {"distributorId":"289407","name":"PATEL INDANE GRAMIN VITRAK"},
    {"distributorId":"290159","name":"TRINITY INDANE"},
    {"distributorId":"292331","name":"SREE GURU INDANE"},
    {"distributorId":"308580","name":"RUPA INDANE GRAMIN VITRAK"},
    {"distributorId":"310646","name":"M/S. PAPANNAPET INDANE"},
    {"distributorId":"312409","name":"M/S. HATHNOORA INDANE"},
    {"distributorId":"315521","name":"SAI KEERTHANA INDANE GRAMIN VITRAK"},
    {"distributorId":"316271","name":"M/S NEELIMA INDANE"},
    {"distributorId":"318304","name":"JAGRUTHI INDANE"},
    {"distributorId":"323963","name":"VARALAKSHMI INDANE DKV"},
    {"distributorId":"324050","name":"SRIKARA INDANE GV"},
    {"distributorId":"351755","name":"RAJPET INDANE DKV"},
    {"distributorId":"125328","name":"7TH BN. APSP GAS AGENCY"},
    {"distributorId":"125332","name":"L V REDDY GAS SERVICE"},
    {"distributorId":"125334","name":"SPHURTHY GAS AGENCY"},
    {"distributorId":"125335","name":"SRI MANIKANTA GAS SERVICE"},
    {"distributorId":"125337","name":"JAYKAY GAS SERVICE"},
    {"distributorId":"125339","name":"BINDUSAKTHI GAS SERVICE"},
    {"distributorId":"125343","name":"ENNAR GAS SERVICE"},
    {"distributorId":"125347","name":"SAIEESH ENTERPRISES"},
    {"distributorId":"125348","name":"ESHWARA AGENCIES"},
    {"distributorId":"125451","name":"UPPAL GAS SERVICE"},
    {"distributorId":"125468","name":"AIR FORCE GAS AGENCY"},
    {"distributorId":"125476","name":"KESHOGIRI GAS AGNECY"},
    {"distributorId":"125493","name":"SRI SAI BALAJI GAS AGENCY"},
    {"distributorId":"125498","name":"SRI SAISUPPLIERS"},
    {"distributorId":"125507","name":"BHAGYANAGAR GAS AGENCIES"},
    {"distributorId":"183886","name":"SHIVAM INDANE"},
    {"distributorId":"188964","name":"KAVITHA INDANE"},
    {"distributorId":"189238","name":"KEDARESHWARA INDANE"},
    {"distributorId":"190023","name":"MAHESHWARA INDANE"},
    {"distributorId":"196711","name":"PANDURANGA INDANE"},
    {"distributorId":"235153","name":"NIZAMABAD INDANE"},
    {"distributorId":"254924","name":"HARI HARA INDANE GRAMIN VITRAK"},
    {"distributorId":"255762","name":"SAHITH INDANE GRAMIN VITRAK"},
    {"distributorId":"256523","name":"GANGA BHAVANI INDANE GRAMIN VITARAK"},
    {"distributorId":"264067","name":"RATHNA INDANE GRAMIN VITRAK"},
    {"distributorId":"275199","name":"DEVI INDANE GRAMIN VITRAK"},
    {"distributorId":"286444","name":"OM SRI NAVA DURGA INDANE"},
    {"distributorId":"287446","name":"NAVANEETHA INDANE"},
    {"distributorId":"288076","name":"SAI SHANKARA INDANE"},
    {"distributorId":"288363","name":"SABARIGIREESHA INDANE"},
    {"distributorId":"295434","name":"PRABHU KRUPA INDANE"},
    {"distributorId":"297245","name":"SAI SHAKTHI INDANE"},
    {"distributorId":"297445","name":"JAYKAY ADHOC YASHODA"},
    {"distributorId":"311497","name":"KATYAYANI INDANE"},
    {"distributorId":"314252","name":"VIKASNI INDANE"},
    {"distributorId":"314562","name":"LIMBADRI NARASIMHA SWAMY INDANE DKV"},
    {"distributorId":"314822","name":"SRI GAYATHRI INDANE"},
    {"distributorId":"318617","name":"BHAGAVATHI INDANE"},
    {"distributorId":"320534","name":"RAMESH INDANE DKV"},
    {"distributorId":"333866","name":"SAI SHARATH INDANE DKV"},
    {"distributorId":"125331","name":"ANUPAMA GAS AGENCIES"},
    {"distributorId":"125340","name":"SWAPNA ENTERPRISE"},
    {"distributorId":"125346","name":"NAVARATNA ENTERPRISES"},
    {"distributorId":"125353","name":"TSCSCL,HYD"},
    {"distributorId":"125458","name":"MM ENTERPRISES"},
    {"distributorId":"125459","name":"ADIMALLIK ENTERPRISE"},
    {"distributorId":"125460","name":"VENKATASAI GAS AGENCIES"},
    {"distributorId":"125471","name":"BANJARA GAS SERVICE"},
    {"distributorId":"125472","name":"JYOTHI ENTERPRISES"},
    {"distributorId":"125473","name":"GNS GAS SERVICE"},
    {"distributorId":"125479","name":"SAMPALLY GAS SERVICE"},
    {"distributorId":"125480","name":"MADHAVI GAS AGENCY"},
    {"distributorId":"125481","name":"SHARADA GAS AGENCY"},
    {"distributorId":"125483","name":"AMAR GAS SERVICE"},
    {"distributorId":"125487","name":"MUKUND ENTERPRISES"},
    {"distributorId":"125488","name":"BRIGHTENING GAS"},
    {"distributorId":"125489","name":"SIDDHARTHA ENTERPRISES"},
    {"distributorId":"125494","name":"STERLING GAS SERVICE"},
    {"distributorId":"125495","name":"PADMA GAS SERVICE"},
    {"distributorId":"125503","name":"GOLCONDA GAS AGENCY"},
    {"distributorId":"213151","name":"SENA SEVA GAS AGENCY"},
    {"distributorId":"278011","name":"MCEME GAS AGENCY"},
    {"distributorId":"285982","name":"M/S. BHRAMARAMBA INDANE"},
    {"distributorId":"286099","name":"KEERTHI INDANE"},
    {"distributorId":"286285","name":"AKSHARA INDANE"},
    {"distributorId":"298648","name":"OM SRI SAIBABA INDANE"},
    {"distributorId":"308600","name":"DEEPIKA INDANE"},
    {"distributorId":"314336","name":"SARVESWARA INDANE"},
    {"distributorId":"315271","name":"BRK INDANE"},
    {"distributorId":"316857","name":"M/S DAKSHA INDANE"},
    {"distributorId":"576227","name":"Sena Seva Gas Agency"},
    {"distributorId":"125309","name":"VAYUPUTRA GAS AGENCIES"},
    {"distributorId":"125325","name":"KOUNDINYASA ENTERPRISES"},
    {"distributorId":"125326","name":"SRI RAMA GAS DISTRIBUTORS"},
    {"distributorId":"125333","name":"IV BN APSP GAS AGENCY"},
    {"distributorId":"125336","name":"JAYA GAS AGENCY"},
    {"distributorId":"125345","name":"INDUSHEKHARA GAS AGENCY"},
    {"distributorId":"125351","name":"RR INDANE SERVICE"},
    {"distributorId":"125352","name":"SRI RAJARAJESWARI GAS DISTRIBUTORS"},
    {"distributorId":"125356","name":"WARANGAL DT POLICE GAS CCS"},
    {"distributorId":"188775","name":"DEEPTHI"},
    {"distributorId":"189241","name":"SOMAGIRI INDNAE"},
    {"distributorId":"194852","name":"RACHANA INDANE"},
    {"distributorId":"197261","name":"RAJAVEERU INDANE"},
    {"distributorId":"197384","name":"RAVEENA INDANE"},
    {"distributorId":"199108","name":"SESHA MAA INDANE"},
    {"distributorId":"200061","name":"KAVERI INDANE SERVICE"},
    {"distributorId":"206140","name":"BOGESH INDANE"},
    {"distributorId":"206699","name":"KODANDARAMA INDANE"},
    {"distributorId":"215498","name":"SWARNA INDANE"},
    {"distributorId":"231372","name":"AMOGH INDANE"},
    {"distributorId":"232150","name":"HARI HARA INDANE"},
    {"distributorId":"233033","name":"LAKSHMI GANAPATHY INDANE"},
    {"distributorId":"235212","name":"AKSHAY INDANE"},
    {"distributorId":"237127","name":"RUDRA NARASIMHA INDANE"},
    {"distributorId":"237141","name":"SAI CHAITRA INDANE"},
    {"distributorId":"247015","name":"SRI SAI RAM INDANE"},
    {"distributorId":"253325","name":"MAHALAKSHMI INDANE GRAMIN VITRAK"},
    {"distributorId":"253729","name":"SAI INDANE GRAMIN VITRAK"},
    {"distributorId":"255624","name":"MADANI INDANE GRAMIN VITRAK"},
    {"distributorId":"255830","name":"BADRANNA INDANE"},
    {"distributorId":"256524","name":"SREE SUSRITHA INDANE GRAMIN VI"},
    {"distributorId":"263276","name":"ALEKYA INDANE"},
    {"distributorId":"269362","name":"JHANSI INDANE GRAMIN VITRAK"},
    {"distributorId":"276228","name":"HARINI INDANE GRAMIN VITRAK"},
    {"distributorId":"288616","name":"RAMADUTHA INDANE"},
    {"distributorId":"289786","name":"JAIDEVA INDANE GRAMIN VITRAK"},
    {"distributorId":"291756","name":"SHAILENDRA INDANE"},
    {"distributorId":"291786","name":"PASHUPATHI INDANE"},
    {"distributorId":"291847","name":"SRIDHARA INDANE"},
    {"distributorId":"296596","name":"RAMABHADRA INDANE"},
    {"distributorId":"314737","name":"SRI ANANTHA PADMANABHA SWAMI INDANE"},
    {"distributorId":"320580","name":"KAKATIYA INDANE DKV"},
    {"distributorId":"327088","name":"RAJYALAKSHMI INDANE"},
    {"distributorId":"365870","name":"Sri Mukunda Indane"},
    {"distributorId":"124750","name":"RAASI CEMENT ECCS LTD"},
    {"distributorId":"125402","name":"VIJAY GAS SERVICE"},
    {"distributorId":"125422","name":"MIRYALGUDA GAS AGENCIES"},
    {"distributorId":"125442","name":"POLICE WELFARE GAS AGNS"},
    {"distributorId":"125499","name":"SANGHAMITRA ECCS LTD"},
    {"distributorId":"125519","name":"SRI SARASWATI ENTERPRISES"},
    {"distributorId":"233596","name":"SRI VIVEKANANDA INDANE"},
    {"distributorId":"243020","name":"SRI SAI DURGA INDANE"},
    {"distributorId":"252669","name":"AISHWARYA INDANE"},
    {"distributorId":"253644","name":"PAVANI INDANE GRAMIN VITARAK"},
    {"distributorId":"253649","name":"M BALANARASAIAH INDANE GRAMIN"},
    {"distributorId":"255879","name":"SREE AYYAPPA INDANE GRAMIN VIT"},
    {"distributorId":"255926","name":"SREE VAISHNAVI INDANE GRAMIN"},
    {"distributorId":"255929","name":"SHIVA BALAJI INDANE GRAMIN"},
    {"distributorId":"257935","name":"SRI LAKSHMI VASAVI INDANE GRAMIN"},
    {"distributorId":"258175","name":"DHARMASHASTA INDANE GRAMIN"},
    {"distributorId":"258209","name":"SRI SAI ROHITH INDANE"},
    {"distributorId":"261636","name":"SREELAXMIMANIDEEP INDANE GRAMI"},
    {"distributorId":"273198","name":"LILADHARA INDANE GRAMIN VITRAK"},
    {"distributorId":"273512","name":"SAI SHIVA INDANE GRAMIN VITRAK"},
    {"distributorId":"277469","name":"ABHAYA ANJANEYA INDANE GRAMIN"},
    {"distributorId":"277477","name":"JAYASREE INDANE GRAMIN VITARAK"},
    {"distributorId":"277714","name":"SRI SAI SUJITHA INDANE GRAMIN"},
    {"distributorId":"287440","name":"SHIVACHANDRA INDANE"},
    {"distributorId":"288612","name":"SAANVI INDANE"},
    {"distributorId":"289089","name":"SUMEDHA INDANE"},
    {"distributorId":"289343","name":"MANIKYA NILAYA INDANE GRAMIN VITRAK"},
    {"distributorId":"289859","name":"SRI TULJA BHAVANI INDANE GRAMIN VIT"},
    {"distributorId":"289992","name":"YADADRI INDANE"},
    {"distributorId":"304707","name":"CHARUMATHI INDANE"},
    {"distributorId":"314964","name":"SRI INDU INDANE DKV"},
    {"distributorId":"316142","name":"PARVATHY INDANE DKV"},
    {"distributorId":"318718","name":"PRUDHVI INDANE"},
    {"distributorId":"330811","name":"SATHWIK INDANE DKV"},
    {"distributorId":"344123","name":"SRI SHANMUKHA INDANE DKV"},
    {"distributorId":"125308","name":"SRI BALAJI GAS AGENCY SK"},
    {"distributorId":"125310","name":"SCCC STORES LTDRK5"},
    {"distributorId":"125311","name":"SCCC.BELLAMPALLY"},
    {"distributorId":"125314","name":"SUPERINTENDENT OF POLICE"},
    {"distributorId":"125322","name":"KRUPA GAS SUPPLIER"},
    {"distributorId":"125323","name":"SCCC STORES LTDRKP"},
    {"distributorId":"125327","name":"PARAMESHWARI GAS SERVICE"},
    {"distributorId":"125329","name":"SCCC STORES LTD MANDAMARI"},
    {"distributorId":"125330","name":"AMBUJA GAS AGENCIES"},
    {"distributorId":"125341","name":"NAIK GAS SERVICE"},
    {"distributorId":"125342","name":"K N GAS SERVICE"},
    {"distributorId":"125344","name":"SAI KISHAN ENTERPRISES"},
    {"distributorId":"125349","name":"PRASHANTH ENTERPRISES"},
    {"distributorId":"125355","name":"KESORAM CONSUMER COOP STORES"},
    {"distributorId":"125457","name":"INTEGRATED TRIBAL DEVELOPMENT AG"},
    {"distributorId":"125470","name":"SCCC LTD GK"},
    {"distributorId":"125474","name":"SRI SATYANARAYANA GAS DIST"},
    {"distributorId":"125486","name":"SRI MAYI GAS AGENCY"},
    {"distributorId":"125513","name":"SCCC LTD KRISHNA COLONY"},
    {"distributorId":"125514","name":"SCC STORES 8INCLINE RE II COLONY"},
    {"distributorId":"132010","name":"SRI SARASWAT INDANE SERVICES"},
    {"distributorId":"183321","name":"ARUNA INDANE"},
    {"distributorId":"183324","name":"JANAKI RAMA INDANE"},
    {"distributorId":"183325","name":"MALLIKARJUNA INDANE"},
    {"distributorId":"183893","name":"SAROJA INDANE"},
    {"distributorId":"189239","name":"RAMSAI INDANE"},
    {"distributorId":"189240","name":"CHANDRA INDANE"},
    {"distributorId":"189245","name":"VIGNESH INDANE"},
    {"distributorId":"199110","name":"SRI BHUVANESHWARI INDANE"},
    {"distributorId":"199111","name":"SESHA RATNAM INDANE"},
    {"distributorId":"204050","name":"MADHAVA INDANE"},
    {"distributorId":"210619","name":"AMRUTHA INDANE"},
    {"distributorId":"231378","name":"SRI SAI VENKATESWARA INDANE"},
    {"distributorId":"255785","name":"SAI PRANI INDANE GRAMIN VITRAK"},
    {"distributorId":"257664","name":"RANA PRATAP INDANE GRAMIN VITR"},
    {"distributorId":"287072","name":"GEETHA INDANE"},
    {"distributorId":"289342","name":"MYTHRI INDANE"},
    {"distributorId":"289622","name":"VISHVESH INDANE GRAMIN VITRAK"},
    {"distributorId":"289685","name":"NISHITHA INDANE GRAMIN VITRAK"},
    {"distributorId":"289846","name":"SAMRUDHI INDANE"},
    {"distributorId":"290910","name":"DHIKSHITHA INDANE GRAMIN VITRAK"},
    {"distributorId":"293463","name":"RISHI SHANKAR INDANE"},
    {"distributorId":"299831","name":"SAHASRA INDANE"},
    {"distributorId":"305385","name":"SRIRAMPUR INDANE GRAMIN VITRAK"},
    {"distributorId":"307312","name":"JAHNAVI INDANE"},
    {"distributorId":"310493","name":"HRUSHIKESH INDANE"},
    {"distributorId":"314551","name":"GOUTHAM INDANE DKV"},
    {"distributorId":"314557","name":"BHAGYALAXMI INDANE DKV"},
    {"distributorId":"314815","name":"SRI RAJA RAJESWARA INDANE DKV"},
    {"distributorId":"315569","name":"SAI GANGA INDANE DKV"},
    {"distributorId":"329085","name":"PADMAVATHI INDANE DKV"},
    {"distributorId":"124751","name":"SRI LAKSHMINARASIMHA GAS AGENCY"},
    {"distributorId":"125418","name":"TSCSCL-ATMAKUR"},
    {"distributorId":"125462","name":"NOSE GAS AGENCY"},
    {"distributorId":"125501","name":"SRI VENKATESWARA GAS AGENCY"},
    {"distributorId":"125510","name":"SRI VINAYAKA GAS AGENCIES"},
    {"distributorId":"125511","name":"SIVA GAS AGENCY"},
    {"distributorId":"125512","name":"SP MAHABUBNAGAR"},
    {"distributorId":"198270","name":"GAYATRI INDANE"},
    {"distributorId":"199303","name":"LEELA GAS AGENCY"},
    {"distributorId":"205702","name":"VICKY INDANE"},
    {"distributorId":"230786","name":"PALAMOOR INDANE"},
    {"distributorId":"239035","name":"MADNOOR INDANE"},
    {"distributorId":"252005","name":"BHAVANI INDANE -RGGLV"},
    {"distributorId":"252877","name":"SIRI INDANE GRAMIN VITRAK"},
    {"distributorId":"254279","name":"SAI JAGAN INDANE GRAMIN VITRAK"},
    {"distributorId":"254293","name":"BHANU INDANE GRAMIN VITRAK"},
    {"distributorId":"254616","name":"HANUMAN INDANE GRAMIN VITRAK"},
    {"distributorId":"254680","name":"SABAREESWARA INDANE"},
    {"distributorId":"254740","name":"AMRUTHASAI INDANE GRAMIN VITRA"},
    {"distributorId":"255835","name":"PAVANSUTA INDANE GRAMIN VITRAK"},
    {"distributorId":"255915","name":"GOWRI INDANE GRAMIN VITRAK"},
    {"distributorId":"256176","name":"SRI KARTIKA INDANE GRAMIN VITR"},
    {"distributorId":"256209","name":"YASHASREE INDANE GRAMIN VITRAK"},
    {"distributorId":"256806","name":"NETHYA INDANE GRAMIN VITRAK"},
    {"distributorId":"258131","name":"RAGHAVA INDANE GRAMIN VITRAK"},
    {"distributorId":"259241","name":"S.L.V.INDANE GRAMIN VITRAK"},
    {"distributorId":"260798","name":"SANJAY INDANE GRAMIN VITRAK"},
    {"distributorId":"260820","name":"SRI LAKSHMI INDANE GRAMIN VITR"},
    {"distributorId":"262794","name":"BHAVYA INDANE GRAMIN VITRAK"},
    {"distributorId":"263759","name":"SRI SAI BAGHAVENTH INDANE GRAM"},
    {"distributorId":"271388","name":"RAHMAN INDANE GRAMIN VITRAK"},
    {"distributorId":"273194","name":"BHARATAMMA INDANE GRAMIN VITRA"},
    {"distributorId":"273199","name":"SRI SAI AMRUTHA INDANE GRAMIN"},
    {"distributorId":"274114","name":"SRI LAKSHMI SUDHA INDANE G.V"},
    {"distributorId":"274115","name":"HARIHARA PUTRA INDANE GRAMIN"},
    {"distributorId":"276778","name":"OMKARA INDANE GRAMIN VITRAK"},
    {"distributorId":"279710","name":"M/S. SREE BALAJI LAKSHMI"},
    {"distributorId":"281175","name":"SREE CHENNAKESHAVA INDANE G.V."},
    {"distributorId":"286763","name":"GNANESHWAR INDANE GRAMIN VITRAK"},
    {"distributorId":"289084","name":"SREE KISTA SREE INDANE"},
    {"distributorId":"289611","name":"PRANAVI INDANE"},
    {"distributorId":"297683","name":"HEMADRI INDANE GRAMIN VITRAK"},
    {"distributorId":"299435","name":"SRIVALLY INDANE GRAMIN VITRAK"},
    {"distributorId":"314727","name":"DIVYA INDANE"},
    {"distributorId":"322174","name":"SRI NISHANTH INDANE DKV"},
    {"distributorId":"326275","name":"SRI PAVAN SIDDA INDANE"},
    {"distributorId":"336492","name":"RUDHVI INDANE GRAMIN VITRAK"},
    {"distributorId":"337469","name":"JASHUVA INDANE DKV"},
    {"distributorId":"361581","name":"RAVI NAYAK INDANE DKV"},
    {"distributorId":"365812","name":"Sree Veerannaswamy Indane GV"},
    {"distributorId":"125313","name":"N.B.F.A Ltd. EMPLOYEES CONSUMERS"},
    {"distributorId":"125320","name":"SREE SREE GAS AGENCY"},
    {"distributorId":"125321","name":"PRIYADARSHINI CEMENTS ECS"},
    {"distributorId":"125387","name":"SATYASHEEL AGENCIES"},
    {"distributorId":"125432","name":"GIRIJAN PRIMARY COOP"},
    {"distributorId":"125438","name":"(HZ) SRI VENKATESWARA INDANE GAS"},
    {"distributorId":"125463","name":"VISHNUCEMENT ECS"},
    {"distributorId":"125518","name":"SRI JAIGURUDATTA GAS AGENCIES"},
    {"distributorId":"125580","name":"RAVICHANDRA GAS AGENCY"},
    {"distributorId":"125581","name":"POLICE WELFARE GAS AGENCY"},
    {"distributorId":"125584","name":"(SATT) SRI VENKATESWRA INDANE GAS"},
    {"distributorId":"190043","name":"NAGASAI INDANE"},
    {"distributorId":"195322","name":"MAHITHA INDANE GAS SERVICE"},
    {"distributorId":"231201","name":"INDIRA INDANE"},
    {"distributorId":"233210","name":"SAI LIKITHA INDANE"},
    {"distributorId":"252246","name":"DECCAN CEMENTS EMPLOYEES CONSUMERS"},
    {"distributorId":"252984","name":"SRI YADAGIRINARASIMHA INDANEGRAMINV"},
    {"distributorId":"253643","name":"SREE ANJANEYA INDANE GRAMIN VITRAK"},
    {"distributorId":"253998","name":"SRIMYSAMMA INDANE GRAMIN VITRK"},
    {"distributorId":"255518","name":"SRISAIRAMYA INDANE GRAMIN VITRAK"},
    {"distributorId":"257934","name":"JANAKI INDANE GRAMIN VITRAK"},
    {"distributorId":"258596","name":"SRI BHUPATHI INDANE GRAMIN VIT"},
    {"distributorId":"261561","name":"THE PRESIDENT, M/S. NCL INDUSTRIES,"},
    {"distributorId":"264737","name":"VARNIKA INDANE GRAMIN VITRAK"},
    {"distributorId":"273513","name":"LITHIN RAJIV GANDHI INDANE GRA"},
    {"distributorId":"273713","name":"HARI KRISHNA INDANE GRAMIN VIT"},
    {"distributorId":"277449","name":"SRI VAIKUNTAM INDANE GRAMIN VITRAK"},
    {"distributorId":"280404","name":"SRI SATYA SUDHEER INDANE GRAMI"},
    {"distributorId":"284283","name":"VISHNUPRIYA INDANE GRAMIN VITR"},
    {"distributorId":"288805","name":"SRI KANIPAKAM VIGNESHWARA INDANE"},
    {"distributorId":"288932","name":"SRI CHILAKALAGANDI MUTYALAMMA INDAN"},
    {"distributorId":"289085","name":"ANJAN INDANE"},
    {"distributorId":"289842","name":"SHLOKA INDANE"},
    {"distributorId":"290810","name":"SRI CHINMAYANANDA INDANE"},
    {"distributorId":"296594","name":"SRI YOGANANDHA INDANE"},
    {"distributorId":"297117","name":"SRI HANUMAN DATTA SAI INDANE"},
    {"distributorId":"319163","name":"GADIPALLI LAXMI INDANE"},
    {"distributorId":"320505","name":"SAI THIRUMALA INDANE"},
    {"distributorId":"320581","name":"SUBHADRATHA INDANE"},
    {"distributorId":"330449","name":"SAYUDHA JYOTHI INDANE GAS AGENCY"},
    {"distributorId":"336586","name":"SRI SRI BALAJI INDANE DKV"},
    {"distributorId":"370664","name":"SRI SAMMAKKA SARAKKA INDANE DKV"},
    {"distributorId":"125354","name":"SRI SRINIVASA GAS SERVICE"},
    {"distributorId":"125464","name":"AP POLICE ACADEMY INDANE SERVICE"},
    {"distributorId":"125465","name":"SREE SHIRDI SAI INDANE SERVICE"},
    {"distributorId":"125467","name":"PRIYANKA GAS SERVICE"},
    {"distributorId":"125469","name":"BR GAS SERVICE"},
    {"distributorId":"125475","name":"GURUDATTA GAS SERVICE"},
    {"distributorId":"125492","name":"BHARGAVI GAS AGENCY"},
    {"distributorId":"125496","name":"SRI SAILA GAS SERVICE"},
    {"distributorId":"125515","name":"AGNIDHWAJ INDANE SERVICE"},
    {"distributorId":"180270","name":"NARAHARI INDANE"},
    {"distributorId":"189244","name":"PRASANNA INDANE"},
    {"distributorId":"189653","name":"PRAVALLIKA INDANE"},
    {"distributorId":"191461","name":"HARI NARAYANA INDANE"},
    {"distributorId":"245222","name":"MIRDODDI INDANE"},
    {"distributorId":"253572","name":"S.V.R. INDANE GRAMIN VITRAK"},
    {"distributorId":"286324","name":"SREE ANANYA INDANE GRAMIN VITARAK"},
    {"distributorId":"286748","name":"RUMA INDANE"},
    {"distributorId":"287054","name":"SRI VENKATA RAMANA INDANE"},
    {"distributorId":"287634","name":"SAI KIRAN INDANE"},
    {"distributorId":"287714","name":"SRI NEELAKANTA INDANE"},
    {"distributorId":"288254","name":"VAMSHADHARA INDANE"},
    {"distributorId":"290506","name":"MSP INDANE"},
    {"distributorId":"292159","name":"TEJASWI INDANE"},
    {"distributorId":"293226","name":"VANITHA INDANE"},
    {"distributorId":"295260","name":"VIVAAN INDANE"},
    {"distributorId":"304716","name":"RAMABANTU INDANE"},
    {"distributorId":"306309","name":"SRI NIJA INDANE"},
    {"distributorId":"313192","name":"TRIVIKRAMA INDANE"},
    {"distributorId":"314107","name":"SRI HAINDHAVI INDANE"},
    {"distributorId":"326984","name":"MADDURI INDANE"},
    {"distributorId":"327087","name":"VENKATESHWARA INDANE DKV"},
    {"distributorId":"347168","name":"Parameshwara Indane"}
    
]
  